#!/usr/bin/env node
/**
 * sync-catalog — keep src/app/cards/catalog.json (the canonical source)
 * and the inlined `catalog` object inside src/app/functions/create-quote.js
 * in lock-step.
 *
 * Background: HubSpot's app-function deploy bundles the entrypoint .js
 * plus node_modules and nothing else — sibling .json/.js files referenced
 * via require() are not shipped, and the docs forbid `file:` dependencies.
 * Inlining is the only way to share static data with the function.
 *
 * Usage:
 *   node scripts/sync-catalog.mjs          # update create-quote.js in place
 *   node scripts/sync-catalog.mjs --check  # exit 1 if drift, no writes (for CI)
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const catalogPath = resolve(root, 'src/app/cards/catalog.json');
const functionPath = resolve(root, 'src/app/functions/create-quote.js');

const START = '// CATALOG_START — generated by scripts/sync-catalog.mjs. Edit src/app/cards/catalog.json instead.';
const END = '// CATALOG_END';

const checkOnly = process.argv.includes('--check');

const catalogJson = readFileSync(catalogPath, 'utf8').trim();
const fn = readFileSync(functionPath, 'utf8');

const startIdx = fn.indexOf(START);
const endIdx = fn.indexOf(END);

if (startIdx === -1 || endIdx === -1) {
  console.error(
    `Sentinels not found in ${functionPath}. Expected:\n  ${START}\n  ${END}`
  );
  process.exit(2);
}

const before = fn.slice(0, startIdx + START.length);
const after = fn.slice(endIdx);
const generated = `\nconst catalog = ${catalogJson};\n`;
const updated = before + generated + after;

if (updated === fn) {
  console.log('catalog: in sync ✓');
  process.exit(0);
}

if (checkOnly) {
  console.error(
    'catalog: DRIFT — src/app/cards/catalog.json has changed but create-quote.js is stale.\n' +
      'Run: node scripts/sync-catalog.mjs'
  );
  process.exit(1);
}

writeFileSync(functionPath, updated);
console.log('catalog: synced into create-quote.js');
